/** Default name patterns generated by the editor (Event_1, Action_2, NewEvent, etc.) */
const DEFAULT_PATTERNS: Record<string, RegExp> = {
  event: /^(Event_\d+|NewEvent)$/,
  action: /^(Action_\d+|NewAction)$/,
};

/**
 * Returns true if the name is user-assigned (i.e. NOT a default auto-generated name).
 * Used to decide whether to show the name prefix in the composer view.
 */
export function isCustomName(name: string, kind: 'event' | 'action'): boolean {
  if (!name) return false;
  return !DEFAULT_PATTERNS[kind].test(name);
}
